### ISSUE TITLE
npe_default_arg(func, param, value) not working

### ISSUE THREAD

**Issue by skoch9** [fwilliams/numpyeigen#31]
Something is defunct when default arguments are bound: 
`npe_default_arg(read_normals, bool, true)`
gives the following error when called:
`v, f, _ = igl.readOFF(igl.tutorial_path + "cube.off", read_normals=False)`

```
TypeError: readOFF(): incompatible function arguments. The following argument types are supported:
    1. (read_normals: str=True, str: bool) -> Tuple[object, object, object]
```
Can be replicated with branch npe_bugs of libigl repo

**Comment by fwilliams** [comment]
This works locally for me in the `npe_bugs` branch. What version is your branch of NumpyEigen pointing to?

Also the tests for default arguments pass in NumpyEigen. 

This and #32 might be a config issue.
