### ISSUE TITLE
Link to the example project in the README is broken

### ISSUE THREAD

**Issue by kshitijgoel007** [fwilliams/numpyeigen#49]
The link provided to the the NumpyEigen-Example-Project in the readme currently says 402 not found.

**Comment by fwilliams** [comment]
Hey thanks for reporting the issue. I broke the API a while back and made the repo private. I fixed it yesterday and I'll make it public later today. Sorry about that!

**Comment by fwilliams** [comment]
Hey, this is now fixed and [the example project is live](https://github.com/fwilliams/numpyeigen-example-project). Thanks for your patience!
