### ISSUE TITLE
Install failed

### ISSUE THREAD

**Issue by ivansipiran** [fwilliams/numpyeigen#50]
Hi, it seems the URL to Eigen is broken.

**Comment by fwilliams** [comment]
Hi @ivansipiran 

Thanks for letting me know! Could you paste the command you ran and the error you got so I can fix it?

**Comment by ivansipiran** [comment]
Hi @fwilliams,

during cmake, the output is (the problem is Eigen, which is not available from bitbucket):

-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Clonando en 'numpyeigen'...
Nota: actualizando el árbol de trabajo '05a22ad4f06a431bffc3860b30c00cf89e81373b'.

Te encuentras en estado 'detached HEAD'. Puedes revisar por aquí, hacer
cambios experimentales y confirmarlos, y puedes descartar cualquier
commit que hayas hecho en este estado sin impactar a tu rama realizando
otro checkout.

Si quieres crear una nueva rama para mantener los commits que has creado,
puedes hacerlo (ahora o después) usando -b con el comando checkout. Ejemplo:

  git checkout -b <nombre-de-nueva-rama>

HEAD está ahora en 05a22ad 0D arrays
-- Performing Test COMPILER_SUPPORT_OPENMP
-- Performing Test COMPILER_SUPPORT_OPENMP - Success
CMake Warning (dev) at external/numpyeigen/cmake/numpyeigen.cmake:98 (set):
  Cannot set "NPE_ROOT_DIR": current scope has no parent.
Call Stack (most recent call first):
  CMakeLists.txt:21 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at .cache/eigen/eigen-download-prefix/src/eigen-download-stamp/download-eigen-download.cmake:159 (message):
  Each download failed!

    error: downloading 'http://bitbucket.org/eigen/eigen/get/3.3.7.tar.bz2' failed
         status_code: 22
         status_string: "HTTP response code said error"
         log:
         --- LOG BEGIN ---
           Trying 18.205.93.0:80...

  Connected to bitbucket.org (18.205.93.0) port 80 (#0)

  GET /eigen/eigen/get/3.3.7.tar.bz2 HTTP/1.1

  Host: bitbucket.org

  User-Agent: curl/7.71.1

  Accept: */*

  

  Mark bundle as not supporting multiuse

  HTTP/1.1 301 Moved Permanently

  Content-Type: text/html

  Date: Mon, 24 Aug 2020 16:49:22 GMT

  Location: https://bitbucket.org/eigen/eigen/get/3.3.7.tar.bz2

  Connection: Keep-Alive

  Content-Length: 0

  

  Connection #0 to host bitbucket.org left intact

  Issue another request to this URL:
  'https://bitbucket.org/eigen/eigen/get/3.3.7.tar.bz2'

    Trying 18.205.93.2:443...

  Connected to bitbucket.org (18.205.93.2) port 443 (#1)

  ALPN, offering h2

  ALPN, offering http/1.1

  successfully set certificate verify locations:

    CAfile: /etc/ssl/certs/ca-certificates.crt
    CApath: /etc/ssl/certs

  [5 bytes data]

**Comment by fwilliams** [comment]
This was fixed in #51
