### ISSUE TITLE
Eigen not found

### ISSUE THREAD

**Issue by kimihailv** [fwilliams/numpyeigen#56]
Hello, when I try to install library this error occurs:

Cloning into 'eigen'...
  remote: A repository for this project does not exist yet.
  fatal: repository 'https://gitlab.com/libeigen/eigen.git/' not found

**Comment by JonasBreuling** [comment]
The gitlab repo is broken since saturday. So its an expected problem.

kimihailv ***@***.***> schrieb am Mo., 4. Okt. 2021, 17:59:
