### ISSUE TITLE
What is numpy_hacks_stable ?

### ISSUE THREAD

**Issue by alecjacobson** [fwilliams/numpyeigen#58]
I noticed some 

"Encapsulate move!" being printed in new libigl python bindings I was working on. I've tracked it down to https://github.com/fwilliams/pybind11/tree/numpy_hacks_stable

What does this error message mean? Is it necessary to print?

**Comment by fwilliams** [comment]
It does look like that print is completely unnecessary! NumpyEigen needs some fields from the `PyArrayObject` struct which were not exposed in pybind11, so I have this branch which exposes these fields. I also remember modifying the sparse matrix type caster a bit but don't remember exactly why I needed to do this.

The main changes are here: https://github.com/fwilliams/pybind11/commit/aeda673cec1aa616ac160d1f54db3b2edd3d9a93

As for that `cerr` it's completely superflous and I'll delete it. Good catch!

I should probably send an upstream PR at some point but never got around to doing it.

**Comment by fwilliams** [comment]
I just removed the print statement. If you remove the cached numpyeigen dependency locally and rebuild libigl, you shouldn't see this message anymore.
